### ISSUE TITLE
运行 ./start 报错

### ISSUE THREAD

**Issue by orzhtml** [osmartian/weex-frame#21]
weex-frame-0.1.1 ./start
~/website/github/weex-frame-0.1.1 ~/website/github/weex-frame-0.1.1

> weex-frame@0.1.0 dev /Users/carson/website/github/weex-frame-0.1.1
> webpack --watch

> weex-frame@0.1.0 serve /Users/carson/website/github/weex-frame-0.1.1
> node build/ip.js && serve -p 8080

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at Function.app.listen (/Users/carson/website/github/weex-frame-0.1.1/node_modules/_connect@2.3.9@connect/lib/proto.js:229:24)
    at Object.<anonymous> (/Users/carson/website/github/weex-frame-0.1.1/node_modules/_serve@1.4.0@serve/bin/serve:132:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/carson/.nvm/versions/node/v6.10.3/bin/node" "/Users/carson/.nvm/versions/node/v6.10.3/bin/npm" "run" "serve"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! weex-frame@0.1.0 serve: `node build/ip.js && serve -p 8080`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weex-frame@0.1.0 serve script 'node build/ip.js && serve -p 8080'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the weex-frame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/ip.js && serve -p 8080
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs weex-frame
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls weex-frame
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/carson/website/github/weex-frame-0.1.1/npm-debug.log
Hash: 929a150176d992f0a542
Version: webpack 1.15.0
Time: 8764ms
                                Asset    Size  Chunks             Chunk Names
                weex/views/404/app.js  117 kB       9  [emitted]  views/404/app
                          weex/App.js  118 kB       0  [emitted]  App
    weex/components/osc-list/index.js  115 kB       2  [emitted]  components/osc-list/index
        weex/components/osc-navbar.js  115 kB       3  [emitted]  components/osc-navbar
       weex/components/osc-navpage.js  115 kB       4  [emitted]  components/osc-navpage
          weex/components/osc-root.js  115 kB       5  [emitted]  components/osc-root
weex/components/osc-scroller/index.js  115 kB       6  [emitted]  components/osc-scroller/index
        weex/components/osc-tabbar.js  115 kB       7  [emitted]  components/osc-tabbar
       weex/components/osc-tabitem.js  115 kB       8  [emitted]  components/osc-tabitem
                      weex/App.web.js  118 kB       1  [emitted]  App.web
               weex/views/home/app.js  115 kB      10  [emitted]  views/home/app
             weex/views/launch/app.js  115 kB      11  [emitted]  views/launch/app
               weex/views/list/app.js  115 kB      12  [emitted]  views/list/app
               weex/views/mine/app.js  115 kB      13  [emitted]  views/mine/app
           weex/views/personal/app.js  115 kB      14  [emitted]  views/personal/app
           weex/views/scroller/app.js  115 kB      15  [emitted]  views/scroller/app
           weex/views/userinfo/app.js  115 kB      16  [emitted]  views/userinfo/app
                weex/views/web/app.js  115 kB      17  [emitted]  views/web/app
   [0] ./src/entry/views/mine/app.js?entry=true 535 bytes {13} [built]
   [0] ./src/entry/App.js?entry=true 518 bytes {0} [built]
   [0] ./src/entry/views/userinfo/app.js?entry=true 539 bytes {16} [built]
   [0] ./src/entry/views/scroller/app.js?entry=true 539 bytes {15} [built]
   [0] ./src/entry/views/personal/app.js?entry=true 539 bytes {14} [built]
   [0] ./src/entry/views/web/app.js?entry=true 534 bytes {17} [built]
   [0] ./src/entry/views/list/app.js?entry=true 535 bytes {12} [built]
   [0] ./src/entry/views/launch/app.js?entry=true 537 bytes {11} [built]
   [0] ./src/entry/views/home/app.js?entry=true 535 bytes {10} [built]
   [0] ./src/entry/views/404/app.js?entry=true 534 bytes {9} [built]
   [0] ./src/entry/App.web.js?entry=true 522 bytes {1} [built]
    + 92 hidden modules
Hash: 0e5fcffd81f1c837ac67
Version: webpack 1.15.0
Time: 8960ms
   Asset    Size  Chunks             Chunk Names
entry.js  431 kB       0  [emitted]  entry
    + 115 hidden modules
Hash: 929a150176d992f0a542
Version: webpack 1.15.0
Time: 112ms
                                Asset    Size  Chunks             Chunk Names
                weex/views/404/app.js  117 kB       9  [emitted]  views/404/app
                          weex/App.js  118 kB       0  [emitted]  App
    weex/components/osc-list/index.js  115 kB       2  [emitted]  components/osc-list/index
        weex/components/osc-navbar.js  115 kB       3  [emitted]  components/osc-navbar
       weex/components/osc-navpage.js  115 kB       4  [emitted]  components/osc-navpage
          weex/components/osc-root.js  115 kB       5  [emitted]  components/osc-root
weex/components/osc-scroller/index.js  115 kB       6  [emitted]  components/osc-scroller/index
        weex/components/osc-tabbar.js  115 kB       7  [emitted]  components/osc-tabbar
       weex/components/osc-tabitem.js  115 kB       8  [emitted]  components/osc-tabitem
                      weex/App.web.js  118 kB       1  [emitted]  App.web
               weex/views/home/app.js  115 kB      10  [emitted]  views/home/app
             weex/views/launch/app.js  115 kB      11  [emitted]  views/launch/app
               weex/views/list/app.js  115 kB      12  [emitted]  views/list/app
               weex/views/mine/app.js  115 kB      13  [emitted]  views/mine/app
           weex/views/personal/app.js  115 kB      14  [emitted]  views/personal/app
           weex/views/scroller/app.js  115 kB      15  [emitted]  views/scroller/app
           weex/views/userinfo/app.js  115 kB      16  [emitted]  views/userinfo/app
                weex/views/web/app.js  115 kB      17  [emitted]  views/web/app
    + 103 hidden modules

**Comment by orzhtml** [comment]
噢，端口被占用了。
