### ISSUE TITLE
直接部署有问题

### ISSUE THREAD

**Issue by hahafeixiu** [osmartian/weex-frame#32]
我是刚接触weex，没有前端的经验；所以按照你的项目步鄹去部署；出现以下问题（因为我是小白，所以如果有解决办法是否能回答的详细点，万分感谢！）：
ERROR in ./src/entry.js
Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (/Users/ge-boox/Downloads/git_other/weex-frame/node_modules/babel-loader/lib/utils/exists.js:7:25)
    at find (/Users/ge-boox/Downloads/git_other/weex-frame/node_modules/babel-loader/lib/resolve-rc.js:13:9)
    at Object.module.exports (/Users/ge-boox/Downloads/git_other/weex-frame/node_modules/babel-loader/lib/index.js:113:132)

ERROR in ./~/weex-vue-loader/lib/script-loader.js!./~/babel-loader/lib!./~/weex-vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
Module build failed: TypeError: fileSystem.statSync is not a function

**Comment by Lanceloft** [comment]
根目录修改package.json,把babel-loader改为^6.1.1即可

**Comment by walid1992** [comment]
@hahafeixiu 已降级 babel-loader 至 6.4.1
